import streamlit as st
import pandas as pd
from datetime import datetime

# -------------------------------------------------
# Page Config
# -------------------------------------------------
st.set_page_config(
    page_title="Application Validation Checklist",
    layout="wide"
)

st.title("Application Validation Checklist")

# -------------------------------------------------
# Mandatory Header Details
# -------------------------------------------------
st.subheader("Mandatory Details")

col1, col2, col3 = st.columns(3)

with col1:
    programmer_name = st.text_input("Programmer Name *")

with col2:
    programme = st.selectbox(
        "Programme *",
        ["", "KEAM", "BPHARM", "ENGINEERING", "PG", "MEDICAL"]
    )

with col3:
    category = st.selectbox(
        "Category *",
        ["", "Development", "Testing", "Audit", "Production"]
    )

mandatory_ok = all([
    programmer_name.strip(),
    programme,
    category
])

if not mandatory_ok:
    st.warning("All mandatory fields (*) must be filled to proceed.")

st.divider()

# -------------------------------------------------
# Checklist Master (FROM YOUR TABLE)
# -------------------------------------------------
CHECKLIST = {
    "Application Setup": [
        ("Prospectus Upload", "Prospectus uploading"),
        ("Academic Year Configuration", "Correct academic year configured"),
        ("Age Limit Configuration", "Age limits set as per prospectus"),
        ("Certificate Format Configuration", "Certificate formats as per prospectus"),
    ],
    "Applicant Support": [
        ("Help Documentation Availability", "How to Apply, Fee Payment, Image Upload, Prerequisites"),
        ("Contact Information", "Helpdesk / Contact number"),
    ],
    "Access & Recovery": [
        ("Forgot Application Number", "Retrieval functionality working"),
        ("Forgot Password", "Password reset working correctly"),
        ("OTP Verification", "OTP generation and validation"),
    ],
    "Application Creation": [
        ("New Application Creation", "Application creation in local/live environment"),
        ("Field Validation", "Mandatory and optional fields validation"),
        ("Button & Navigation Check", "All menus and buttons functioning"),
        ("Save Draft / Resume", "Draft save and resume works"),
    ],
    "Application Submission": [
        ("Final Submission", "Submission successful without errors"),
    ],
    "Fee Management": [
        ("Application Fee – General", "Fee configuration for General category"),
        ("Application Fee – SC/ST", "Fee configuration for SC/ST category"),
        ("Payment Gateway Integration", "Payment gateway functionality"),
        ("Payment Handling", "Success / failure handling"),
    ],
    "Photo & Documents": [
        ("Live Photo Capture", "Live photo capture working"),
        ("Image Upload Validation", "Size, format, clarity validated"),
        ("Document Upload", "Certificates uploaded correctly"),
    ]
}

# -------------------------------------------------
# View Selector
# -------------------------------------------------
view_type = st.radio(
    "Select View",
    ["Checklist View", "Report View"],
    horizontal=True,
    disabled=not mandatory_ok
)

# -------------------------------------------------
# Checklist View
# -------------------------------------------------
if view_type == "Checklist View" and mandatory_ok:
    st.subheader("Checklist Verification")

    checklist_data = []

    for section, items in CHECKLIST.items():
        st.markdown(f"### {section}")

        for item, desc in items:
            col1, col2, col3 = st.columns([3, 4, 2])

            with col1:
                st.markdown(f"**{item}**")

            with col2:
                st.caption(desc)

            with col3:
                status = st.selectbox(
                    "Status",
                    ["Pending", "OK", "Not OK", "NA"],
                    key=f"{section}_{item}"
                )

            remarks = st.text_input(
                "Remarks (if any)",
                key=f"remark_{section}_{item}"
            )

            checklist_data.append({
                "Section": section,
                "Checklist Item": item,
                "Description": desc,
                "Status": status,
                "Remarks": remarks
            })

    if st.button("Generate Checklist Report"):
        st.success("Checklist report generated successfully.")

        df = pd.DataFrame(checklist_data)

        st.subheader("Checklist Summary")
        st.dataframe(df, use_container_width=True, hide_index=True)

        st.caption(
            f"Generated by **{programmer_name}** | "
            f"Programme: **{programme}** | "
            f"Category: **{category}** | "
            f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}"
        )

# -------------------------------------------------
# Report View (Read-only)
# -------------------------------------------------
if view_type == "Report View" and mandatory_ok:
    st.subheader("Checklist Report View")

    rows = []
    for section, items in CHECKLIST.items():
        for item, desc in items:
            rows.append({
                "Application Area": section,
                "Checklist Item": item,
                "Validation Points": desc
            })

    df = pd.DataFrame(rows)

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )

# -------------------------------------------------
# Footer
# -------------------------------------------------
st.divider()
st.caption("© Application Validation Checklist | Internal / Audit Use Only")
